version: 2.1
executors:
  perl:
    docker:
      - image: perl:5.30
    working_directory: ~/repo

commands:
  restore_global_deps:
    steps:
      - restore_cache:
          keys:
            - v1-global-deps-{{ .Branch }}-{{ .Revision }}
            - v1-global-deps-{{ .Branch }}-
            - v1-global-deps-

  save_global_deps:
    steps:
      - save_cache:
          paths:
            - /usr/local/bin/carton
            - /usr/local/lib/perl5/site_perl/5.30.0
          key: v1-global-deps-{{ .Branch }}-{{ .Revision }}

  restore_repo:
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ .Revision }}
            - v1-repo-{{ .Branch }}-
            - v1-repo-

  save_repo:
    steps:
      - save_cache:
          paths:
            - .
          key: v1-repo-{{ .Branch }}-{{ .Revision }}

  restore_deps:
    steps:
      - restore_cache:
          keys:
            - v1-rev30-dependencies-{{ checksum "cpanfile.snapshot" }}
            - v1-rev30-dependencies-

  save_deps:
    steps:
      - save_cache:
          paths:
            - local
          key: v1-rev30-dependencies-{{ checksum "cpanfile.snapshot" }}

jobs:
  checkout_code:
    executor: perl
    steps:
      - restore_repo
      - checkout
      - save_repo

  install_deps:
    executor: perl
    steps:
      - restore_repo
      - restore_global_deps
      - restore_deps
      - run: cpanm Carton --notest
      - run: carton install --deployment
      - save_global_deps
      - save_deps

  test:
    executor: perl
    steps:
      - restore_repo
      - restore_global_deps
      - restore_deps
      - run: carton exec prove ./t/

  generate_atok:
    executor: perl
    steps:
      - restore_repo
      - restore_global_deps
      - restore_deps
      - run:
          name: Generate dictionaries for ATOK
          command: |
            ./bin/runner.sh Generators::Atok Kaomojic ./dist/atok/kaomojic
            ./bin/runner.sh Generators::Atok Ekimemo  ./dist/atok/ekimemo
      - save_cache:
          paths:
            - ./dist/atok
          key: v1-releases-atok-{{ .Branch }}-{{ .Revision }}

  generate_gime:
    executor: perl
    steps:
      - restore_repo
      - restore_global_deps
      - restore_deps
      - run:
          name: Generate dictionaries for Google IME
          command: |
            ./bin/runner.sh Generators::Google Kaomojic ./dist/google-ime/kaomojic
            ./bin/runner.sh Generators::Google Ekimemo  ./dist/google-ime/ekimemo
      - save_cache:
          paths:
            - ./dist/google-ime
          key: v1-releases-google-ime-{{ .Branch }}-{{ .Revision }}

  release:
    executor: perl
    steps:
      - restore_repo
      - restore_cache:
          keys:
            - v1-releases-atok-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          keys:
            - v1-releases-google-ime-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install zip
          command: |
            apt update
            apt install zip -y
      - run: mkdir -p ./releases
      - run:
          name: Packaging dictionaries
          command: |
            zip ./releases/kaomojic-atok-dictionary.zip ./dist/atok/kaomojic/*.txt
            zip ./releases/ekimemo-atok-dictionary.zip  ./dist/atok/ekimemo/*.txt
            zip ./releases/kaomojic-google-ime-dictionary.zip ./dist/google-ime/kaomojic/*.txt
            zip ./releases/ekimemo-google-ime-dictionary.zip  ./dist/google-ime/ekimemo/*.txt
      - run:
          name: Install tcnksm/ghr
          command: |
            wget https://github.com/tcnksm/ghr/releases/download/v0.12.1/ghr_v0.12.1_linux_amd64.tar.gz -O ghr.tar.gz
            mkdir ./ghr
            tar -xvf ./ghr.tar.gz --strip 1 --directory ./ghr
      - run: ./ghr/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} "rev.${CIRCLE_BUILD_NUM}-$(git rev-parse --short HEAD)" ./releases

workflows:
  version: 2.1
  build_accept_release:
    jobs:
      - checkout_code
      - install_deps:
          requires:
            - checkout_code
      - test:
          requires:
            - install_deps
      - generate_atok:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
      - generate_gime:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
      - release:
          requires:
            - generate_atok
            - generate_gime
