version: 2.1
executors:
  perl:
    docker:
      - image: perl:5.28.1
    working_directory: ~/repo

commands:
  restore_bins:
    steps:
      - restore_cache:
          keys:
            - v1-bins-{{ .Branch }}-{{ .Revision }}
            - v1-bins-{{ .Branch }}-
            - v1-bins-

  save_bins:
    steps:
      - save_cache:
          paths:
            - /usr/local/bin/cpanm
          key: v1-bins-{{ .Branch }}-{{ .Revision }}

  restore_repo:
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ .Revision }}
            - v1-repo-{{ .Branch }}-
            - v1-repo-

  save_repo:
    steps:
      - save_cache:
          paths:
            - .
          key: v1-repo-{{ .Branch }}-{{ .Revision }}

  restore_deps:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "cpanfile.snapshot" }}
            - v1-dependencies-

  save_deps:
    steps:
      - save_cache:
          paths:
            - local
          key: v1-dependencies-{{ checksum "cpanfile.snapshot" }}

jobs:
  checkout_code:
    executor: perl
    steps:
      - restore_repo
      - checkout
      - save_repo

  install_deps:
    executor: perl
    steps:
      - restore_repo
      - restore_bins
      - restore_deps
      - run: cpanm Carton --notest
      - run: carton install --deployment
      - save_bins
      - save_deps

  test:
    executor: perl
    steps:
      - restore_repo
      - restore_bins
      - restore_deps
      - install_carton
      - run: carton exec prove ./t/

  generate:
    executor: perl
    steps:
      - restore_repo
      - restore_bins
      - restore_deps
      - install_carton
      - run: carton exec perl generator.pl

  release:
    executor: perl
    steps:
      - run: echo 1

workflows:
  version: 2.1
  build_accept_release:
    jobs:
      - checkout_code
      - install_deps:
          requires:
            - checkout_code
      - test:
          requires:
            - install_deps
      - generate:
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          requires:
            - generate
